// Minimal DOM helpers. Kept framework-free on purpose: Astro ships this
// as a plain module, so views stay dependency-light and easy to test.
//
// NOTE: `worker-configuration.d.ts` (regenerated by `wrangler types`) is
// included in the typecheck. It carries the workerd runtime DOM, whose
// `interface Element` merges with lib.dom's `Element` and adds `remove():
// Element` etc. — so lib.dom element CLASSES like `HTMLSelectElement` stop
// satisfying any `extends Element` constraint. `qs` therefore constrains
// against nothing; its param types name the lib.dom family (real roots) and
// the cast keeps explicit type arguments (e.g. `qs<HTMLSelectElement>`)
// working without every view seeing the ambient shadowed names.

// Non-throwing variant for bindings that attach to OPTIONAL parts of a view
// (e.g. the notes panel that only exists while open). `qs` throws on a miss,
// which would abort the whole wire-up pass and leave buttons like Enviar
// unbound — this one returns `null` so callers use `?.addEventListener`.
export function qsIf<T = HTMLElement>(
  selector: string,
  root: ParentNode | HTMLElement = document
): T | null {
  return root.querySelector(selector) as T | null;
}

export function qs<T = HTMLElement>(
  selector: string,
  root: ParentNode | HTMLElement = document
): T {
  const el = root.querySelector(selector) as unknown as T;
  if (!el) throw new Error(`Element not found: ${selector}`);
  return el;
}

export function qsa<T extends Node = Node>(
  selector: string,
  root: ParentNode | HTMLElement = document
): NodeListOf<T> {
  return root.querySelectorAll(selector) as unknown as NodeListOf<T>;
}

export function mount(root: HTMLElement, html: string): void {
  root.innerHTML = html;
}

export function on<K extends keyof HTMLElementEventMap>(
  root: ParentNode | HTMLElement,
  selector: string,
  type: K,
  handler: (event: HTMLElementEventMap[K], target: HTMLElement) => void
): void {
  root.addEventListener(type, (event) => {
    const target = (event.target as HTMLElement).closest<HTMLElement>(selector);
    if (target && root.contains(target)) {
      handler(event as HTMLElementEventMap[K], target);
    }
  });
}

export function formValues(form: HTMLFormElement): Record<string, string> {
  const data = new FormData(form);
  const values: Record<string, string> = {};
  data.forEach((value, key) => { values[key] = String(value); });
  return values;
}

export function escapeAttr(text: string): string {
  return String(text).replace(/"/g, '&quot;');
}